In [29]:
import verse
import corpus
import generate_sample
import phonetic
import rhymetools
import importlib

dictionary = phonetic.PhoneticDictionary()

In [30]:
importlib.reload(phonetic)
importlib.reload(verse)
importlib.reload(rhymetools)

verse_template = verse.VerseTemplate(verse.get_sample(5), dictionary, breakrules="phrase") 
verse_template.add_unknowns("logios_output/g2p.txt")
print()
print(verse.get_sample(5))
print()
print(verse_template.wordList)
print()
print(verse_template.stresses)
print()
print(verse_template.syllable_indices)
print()
print(verse_template.matrix_indices)
print()
print(verse_template.rhyme_matrix)

verse_template.get_rhyme()

"dawg" not in dictionary
"trigonometry" not in dictionary
"dawg" not in dictionary

Alexander Hamilton, my dawg is Alexander Hamilton. He studies trigonometry, dawg

[phonetic.Word("alexander" AE2 L AH0 G Z AE1 N D ER0 ), phonetic.Word("hamilton" HH AE1 M AH0 L T AH0 N ), phonetic.Word("my" M AY1 ), phonetic.Word("dawg" D AO0 G ), phonetic.Word("is" IH1 Z ), phonetic.Word("alexander" AE2 L AH0 G Z AE1 N D ER0 ), phonetic.Word("hamilton" HH AE1 M AH0 L T AH0 N ), phonetic.Word("he" HH IY1 ), phonetic.Word("studies" S T AH1 D IY0 Z ), phonetic.Word("trigonometry" T R IH0 G AH0 N AH0 M EH0 T R IY0 ), phonetic.Word("dawg" D AO0 G )]

[2, 0, 1, 0, 1, 0, 0, 1, 0, 1, 2, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]

[]

[]

None


AttributeError: 'VerseTemplate' object has no attribute 'num_syllables'

In [8]:
importlib.reload(phonetic)
importlib.reload(verse)
importlib.reload(rhymetools)
importlib.reload(corpus)

corp = corpus.WordCorpus(dictionary)
corp.initialize(verse.get_sample(5), is_filename=False)
print()
print(corp.wordList)
print(corp.wordSeq)
corp.add_unknowns("logios_output/g2p.txt")
print()
print(corp.wordList)
corp.initializeMatrix()
print()
print(corp.wordDict)
corp.initializeSylDict()
print()
print(corp.sylDict)



"dawg" not in dictionary
"trigonometry" not in dictionary
Input text: 11 words, 8 unique

[phonetic.Word("alexander" AE2 L AH0 G Z AE1 N D ER0 ), phonetic.Word("hamilton" HH AE1 M AH0 L T AH0 N ), phonetic.Word("my" M AY1 ), None, phonetic.Word("is" IH1 Z ), phonetic.Word("he" HH IY1 ), phonetic.Word("studies" S T AH1 D IY0 Z ), None]
[0 1 2 3 4 0 1 5 6 7 3]

[phonetic.Word("alexander" AE2 L AH0 G Z AE1 N D ER0 ), phonetic.Word("hamilton" HH AE1 M AH0 L T AH0 N ), phonetic.Word("my" M AY1 ), phonetic.Word("dawg" D AO0 G ), phonetic.Word("is" IH1 Z ), phonetic.Word("he" HH IY1 ), phonetic.Word("studies" S T AH1 D IY0 Z ), phonetic.Word("trigonometry" T R IH0 G AH0 N AH0 M EH0 T R IY0 )]

{'alexander': 0, 'hamilton': 1, 'trigonometry': 7, 'dawg': 3, 'he': 5, 'is': 4, 'my': 2, 'studies': 6}

{'IY1': [(5, 1)], 'IH1': [(4, 0)], 'AE1': [(0, 5), (1, 1)], 'AO0': [(3, 1)], 'IY0': [(6, 4), (7, 11)], 'ER0': [(0, 8)], 'IH0': [(7, 2)], 'AE2': [(0, 0)], 'AY1': [(2, 1)], 'AH0': [(0, 2), (1, 3), (1, 6

In [24]:
import numpy as np
a = np.reshape(np.arange(16), (4, 4))
np.fill_diagonal(a, 0)



In [27]:
rows, cols = np.nonzero(a)
print(rows)
print(cols)
print(len(rows))

[0 0 0 1 1 1 2 2 2 3 3 3]
[1 2 3 0 2 3 0 1 3 0 1 2]
12


In [23]:
b = np.array([[1, 0], [3, 4]])
print(np.nonzero(b))
print(np.where(b != 0))

(array([0, 1, 1]), array([0, 0, 1]))
(array([0, 1, 1]), array([0, 0, 1]))


In [17]:
# np.where(a != 0)
np.nonzero(a)


(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2]))

In [11]:
zip(np.where a != 0)

SyntaxError: invalid syntax (<ipython-input-11-b8aec081f395>, line 1)