https://www.python.org/downloads/release/python-364/

In [91]:
import phonetic
import corpus
import generate_sample
import verse
import re
import nltk
import importlib
import string
import seaborn
import numpy as np
from scipy import sparse
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
dictionary = phonetic.PhoneticDictionary()
nltk.download('gutenberg')
dictionary.import_file("data/cmudict/cmudict-0.7b")

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\Marissa\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [4]:
importlib.reload(corpus)

def get_rhythm_string(template, dictionary):
    
    wordstrings = template.split()
    wordlengths = np.zeros(len(wordstrings),dtype=np.int)
    nonos = string.punctuation + '0123456789'
    meter = []

    for i in range(len(wordstrings)):
        wordstring = wordstrings[i].strip(nonos).lower()
        word = dictionary.lookup(wordstring)
        wordlengths[i] = len(word.rhythm)
        meter.extend(word.rhythm)
    
    return wordlengths, np.array(meter)

In [133]:
importlib.reload(corpus)
importlib.reload(phonetic)
importlib.reload(generate_sample)
importlib.reload(verse)

corp = corpus.WordCorpus(dictionary)
corp.initialize("I know a song that gets on everybody's nerves, everybody's \
nerves, everybody's nerves, oh, I know a song that gets on everybody's nerves\
and this is how it goes", is_filename=False)

template = verse.get_sample(1)
print("Template rhythm: ", template)

wordlengths, rhythm = get_rhythm_string(template, dictionary)
print("\nSample: ", generate_sample.generate_verse(corp, wordlengths, rhythm))

Input text: 28 words, 16 unique
Template rhythm:  How does a bastard, orphan, son of a whore and a scotsman, dropped 	in the middle of a forgotten spot in the caribbean in providence impoverished 	in squalor, grow up to be a hero and a scholar?
probabilities do not sum to 1-try anything

Sample:  is how it DAda DAda know a song that gets on DAda nerves oh i DAda a song daDAda gets on da daDADAda oh DAdada DADAda a DAda that gets on DA nerves DAda nerves oh DAda


In [153]:
corp = corpus.WordCorpus(dictionary)
corp.initialize("alexander_hamilton.txt")

template = verse.get_sample(4)
print("Template rhythm: ", template)

wordlengths, rhythm = get_rhythm_string(template, dictionary)
print("\nSample: ", generate_sample.generate_verse(corp, wordlengths, rhythm))

Input text: 547 words, 256 unique
Template rhythm:  buddy you're a boy make a big noise, playing in the street, gonna be 	a big man some day, you got mud on your face, you big disgrace, kicking your can 	all over the place, singing, we will, we will, rock you, we will, we will, rock you

Sample:  coming up a whore and a lot DA DAda da da in squalor grow up a whore and a lot DA by DA DA in the waves daDA struggled and a whore DAda a whore DAda a whore and the ten his guard up a whore and a


In [152]:
corp = corpus.WordCorpus(dictionary)
emma = nltk.corpus.gutenberg.words('austen-emma.txt')
emma = " ".join(emma)
corp.initialize(emma, is_filename=False)

Input text: 190529 words, 7096 unique


In [121]:
template = verse.get_sample(1)
print("Template rhythm: ", template)

wordlengths, rhythm = get_rhythm_string(template, dictionary)
print("\nSample: ", generate_sample.generate_verse(corp, wordlengths, rhythm))

Template rhythm:  How does a bastard, orphan, son of a whore and a scotsman, dropped 	in the middle of a forgotten spot in the caribbean in providence impoverished 	in squalor, grow up to be a hero and a scholar?

Sample:  i have a very handsome i was a most she had rather i have i never to the idea jane jane the daDADAda and DAdada DADAda her very much i was i had longer i had only


In [146]:
importlib.reload(corpus)
importlib.reload(phonetic)
importlib.reload(generate_sample)
importlib.reload(verse)

for i in range(5):
    template = verse.VerseTemplate(verse.get_sample(i), dictionary, \
                                   breakrules='phrase')
    template.get_rhythm()


 I know a song that gets on everybody's nerves, everybody's 	nerves, everybody's nerves. Oh, I know a song that gets on everybody's nerves, 	and this is how it goes, oh oh oh
[1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 0, 2, 0, 1, 1, 0, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 2, 3, 4, 5, 6, 7, 11, 12, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]

 I know a song that gets on everybody's nerves, everybody's 	nerves, everybody's nerves. Oh, I know a song that gets on everybody's nerves, 	and this is how it goes, oh oh oh
[1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 0, 2, 0, 1, 1, 0, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
[12, 17, 22, 23, 35, 41]

 How does a bastard, orphan, son of a whore and a scotsman, dropped 	in the middle of a forgotten spot in the caribbean in providence impoverished 	in squalor, grow up to be a hero and a scholar?
[1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0

In [3]:
import numpy as np
myarr = np.zeros(10)
myarr[3:6] = 1.0
print(myarr)

[0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]


In [9]:
import numpy as np

A = np.random.randint(10,size=(4,4))
print(A, '\n')
A[A<6] = 0
print(A)

print(np.nonzero(A[1,:])[0])

[[7 1 1 1]
 [4 0 4 7]
 [0 5 9 4]
 [1 9 7 2]] 

[[7 0 0 0]
 [0 0 0 7]
 [0 0 9 0]
 [0 9 7 0]]
[3]
